image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run dev
    - cp -a portfolio/
  artifacts:
    paths: portfolio/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
